bootJar.enabled = true
jar.enabled = false

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'

    runtimeOnly project(":adapter:out:redis")
    runtimeOnly project(":domain")
    runtimeOnly project(":application")
    runtimeOnly project(":adapter:in:http")
    runtimeOnly project(":adapter:out:rdb")
    runtimeOnly project(":adapter:in:websocket")
    runtimeOnly project(":adapter:out:external")
}
