bootJar.enabled = true
jar.enabled = false

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    implementation project(":adapter:out:redis")
    implementation project(":domain")
    implementation project(":application")
    implementation project(":adapter:in:http")
    implementation project(":adapter:out:rdb")
    implementation project(":adapter:out:gms")
}
